### ISSUE TITLE
ssh-key.create: command is missing required arguments

### ISSUE THREAD

**Issue by vbotka** [snoopdouglas/dobro#26] opened 2018-02-14 08:47 UTC
I can't create a droplet and receive this error:

```
$ dobro create test999
[dobro - info] ssh-key: create: 'dobro-bro'
[dobro - error] ssh-key: create: dobro-bro: "{"errors":[{"detail":"(ssh-key.create) command is missing required arguments"}]}"

$ dobro version
0.4.0

$ set | grep DOBRO
DOBRO_DOCTL_EXTRA_ARGS=
DOBRO_NAMESPACE=myns
DOBRO_NEW_DROPLET_ARGS='--region ams3 --size 512mb --image freebsd-11-1-x64'
DOBRO_NEW_DROPLET_TAGS=test
DOBRO_SSH_PRIVATE_KEY=/home/user/.ssh/id_rsa
DOBRO_SSH_PUBLIC_KEY=/home/user/.ssh/id_rsa.pub
```

doctl works fine and "doctl compute droplet list" lists my droplets.

```
$ doctl version 1.7.1-release
Git commit hash: ab54ea4
```

What am I missing? Thank you for your effort.

**Comment by snoopdouglas** [comment] 2018-02-14 14:09
Your commands look fine to me, but I've noticed that the environment variables you've set don't appear to be being picked up, as the created key should be named `dobro-myns` given your setting of `DOBRO_NAMESPACE`.

Could you paste the output of the following?

```
dobro --verbose create test999
```

**Comment by snoopdouglas** [comment] 2018-03-02 13:13
Found the cause: there was an extra `''` being passed as an argument; `dobro compute ssh-key create` doesn't like this.

The fix will be applied to the code [on GitLab](https://gitlab.com/snoopdouglas/dobro) and will be released in v0.4.1.

**Closed by snoopdouglas** 2018-03-02 13:13 UTC

**Comment by vbotka** [comment] 2018-03-05 12:14
I've installed the the version 0.4.1

```
> pip list --format=legacy | grep dobro
dobro (0.4.1)
```

but I received this error

```
> dobro create test999
[dobro - info] ssh-key: create: 'dobro-bro'
[dobro - error] ssh-key: create: dobro-bro: "{"errors":[{"detail":"POST https://api.digitalocean.com/v2/account/keys: 422 SSH Key is already in use on your account"}]}"

```
Thank you for your effort.

**Comment by snoopdouglas** [comment] 2018-03-05 12:54
You'll note the following in the output:

```
422 SSH Key is already in use on your account
```

DigitalOcean does not allow creating the same SSH key under different names. You'll need to either
* Delete the old key
* Create a new key specifically for use with dobro
* Rename the old key `dobro-bro`
